export const ISSUE_BOOK_REQUEST = "ISSUE_BOOK_REQUEST"
export const ISSUE_BOOK_SUCCESS = "ISSUE_BOOK_SUCCESS"
export const ISSUE_BOOK_FAIL = "ISSUE_BOOK_FAIL"

export const ISSUE_BOOK_BYID_REQUEST = "ISSUE_BOOK_BYID_REQUEST"
export const ISSUE_BOOK_BYID_SUCCESS = "ISSUE_BOOK_BYID_SUCCESS"
export const ISSUE_BOOK_BYID_FAIL = "ISSUE_BOOK_BYID_FAIL"

export const ISSUE_BOOK_DETAILS_REQUEST = "ISSUE_BOOK_DETAILS_REQUEST"
export const ISSUE_BOOK_DETAILS_SUCCESS = "ISSUE_BOOK_DETAILS_SUCCESS"
export const ISSUE_BOOK_DETAILS_FAIL = "ISSUE_BOOK_DETAILS_FAIL"

export const ISSUE_BOOK_REMOVE_SUCCESS = "ISSUE_BOOK_REMOVE_SUCCESS"
export const UPDATE_ISSUE_BOOK='UPDATE_ISSUE_BOOK'