export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAIL='CURRENT_USER_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const FORGOT_PASSWORD_REQUEST='FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS='FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL='FORGOT_PASSWORD_FAIL'